catering-marketplace
└── catering-marketplace
|   └── apps
|       └── web
|           └── src
|               └── app
|                   ├── (auth)
|                       ├── login
|                           └── page.tsx
|                       ├── signup
|                           └── page.tsx
|                       ├── forgot-password
|                           └── page.tsx
|                       └── onboarding
|                           └── page.tsx
|                   ├── (account)
|                       ├── layout.tsx
|                       ├── page.tsx
|                       ├── orders
|                           └── page.tsx
|                       ├── saved-caterers
|                           └── page.tsx
|                       ├── events
|                           └── page.tsx
|                       ├── messages
|                           └── page.tsx
|                       ├── reviews
|                           └── page.tsx
|                       ├── payments
|                           └── page.tsx
|                       ├── profile
|                           └── page.tsx
|                   ├── experiences
|                       ├── layout.tsx
|                       ├── page.tsx
|                       └── [id]
|                           ├── page.tsx
|                           ├── quote.tsx
|                           ├── booking.tsx
|                           └── confirmation.tsx
|                   └── components
|                       ├── ExperienceCard.tsx
|                       ├── QuoteForm.tsx
|                       ├── BookingForm.tsx
|                       ├── PaymentForm.tsx
|                       └── ConfirmationMessage.tsx