catering-marketplace
└── catering-marketplace
|   └── apps
|       └── web
|           └── src
|               └── app
|                   ├── (auth)
|                       ├── login
|                           └── page.tsx
|                       ├── signup
|                           └── page.tsx
|                       ├── forgot-password
|                           └── page.tsx
|                       └── onboarding
|                           └── page.tsx
|                   ├── (account)
|                       ├── layout.tsx
|                       ├── page.tsx
|                       ├── account
|                           └── page.tsx
|                       ├── orders
|                           └── page.tsx
|                       ├── saved-caterers
|                           └── page.tsx
|                       ├── events
|                           └── page.tsx
|                       ├── messages
|                           └── page.tsx
|                       ├── reviews
|                           └── page.tsx
|                       ├── payments
|                           └── page.tsx
|                       ├── profile
|                           └── page.tsx
|                   ├── experiences
|                       ├── layout.tsx
|                       ├── page.tsx
|                       ├── [id]
|                           ├── layout.tsx
|                           ├── page.tsx
|                           ├── quote
|                               └── page.tsx
|                           ├── book
|                               └── page.tsx
|                           └── confirmation
|                               └── page.tsx
|                   └── payment
|                       ├── layout.tsx
|                       ├── page.tsx
|                       └── confirmation
|                           └── page.tsx