export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    width: '100%',
    minHeight: 'auto',
    background: 'transparent',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'stretch',
    padding: 0,
    fontFamily:
      '"Google Sans", roboto, "Noto Sans Myanmar UI", "Noto Sans Khmer", arial, sans-serif',
  } as React.CSSProperties,
  content: {
    width: '100%',
    maxWidth: '760px',
    backgroundColor: 'white',
    border: '1px solid #e5e7eb',
    borderRadius: '18px',
    boxShadow: '0 18px 45px rgba(15, 23, 42, 0.08)',
    padding: 'clamp(1.25rem, 4vw, 2rem)',
  } as React.CSSProperties,
  progressContainer: {
    width: '100%',
    height: '6px',
    backgroundColor: '#eef2f7',
    borderRadius: '999px',
    marginBottom: '1.5rem',
    overflow: 'hidden',
  } as React.CSSProperties,
  progressBar: {
    height: '100%',
    background: 'linear-gradient(90deg, #7c3aed, #2563eb)',
    transition: 'width 0.3s ease',
  } as React.CSSProperties,
  stepIndicator: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 34,
    padding: '0 12px',
    borderRadius: 999,
    border: '1px solid #e5e7eb',
    background: '#f8fafc',
    fontSize: '0.8125rem',
    fontWeight: '700',
    color: '#475569',
    whiteSpace: 'nowrap',
  } as React.CSSProperties,
  stepNumber: {
    fontSize: '0.8125rem',
    fontWeight: '700',
    color: '#475569',
  } as React.CSSProperties,
  stepDot: {
    fontSize: '1.5rem',
    color: '#f97316',
  } as React.CSSProperties,
  loadingContainer: {
    minHeight: 'auto',
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'center',
    alignItems: 'center',
    background: 'transparent',
  } as React.CSSProperties,
  loadingSpinner: {
    width: '48px',
    height: '48px',
    border: '4px solid #e5e7eb',
    borderTop: '4px solid #7c3aed',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
    marginBottom: '1rem',
  } as React.CSSProperties,
  loadingText: {
    color: '#64748b',
    fontSize: '1rem',
    margin: 0,
  } as React.CSSProperties,
  onboardingHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '1rem',
    marginBottom: '1rem',
    flexWrap: 'wrap',
  } as React.CSSProperties,
  kicker: {
    margin: '0 0 0.25rem',
    color: '#7c3aed',
    fontSize: '0.75rem',
    fontWeight: 800,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
  } as React.CSSProperties,
  onboardingTitle: {
    margin: 0,
    color: '#151126',
    fontSize: 'clamp(1.25rem, 4vw, 1.6rem)',
    fontWeight: 800,
    lineHeight: 1.2,
  } as React.CSSProperties,
  header: {
    marginBottom: '1.5rem',
    textAlign: 'left' as const,
  } as React.CSSProperties,
  title: {
    fontSize: 'clamp(1.35rem, 4vw, 1.75rem)',
    fontWeight: '800',
    color: '#151126',
    margin: 0,
    marginBottom: '0.5rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
  } as React.CSSProperties,
  subtitle: {
    fontSize: 'clamp(0.875rem, 2vw, 1rem)',
    color: '#6b7280',
    margin: 0,
    lineHeight: '1.5',
  } as React.CSSProperties,
  profileForm: {
    marginTop: '2rem',
  } as React.CSSProperties,
  formGroup: {
    marginBottom: '1.5rem',
  } as React.CSSProperties,
  formRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
    alignItems: 'start',
  } as React.CSSProperties,
  label: {
    display: 'block',
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: '0.75rem',
  } as React.CSSProperties,
  input: {
    width: '100%',
    minHeight: 44,
    padding: '0.7rem 0.9rem',
    border: '1px solid #d8dee8',
    borderRadius: '10px',
    fontSize: '0.875rem',
    color: '#1f2937',
    boxSizing: 'border-box' as const,
    fontFamily: 'inherit',
    background: '#ffffff',
    outline: 'none',
  } as React.CSSProperties,
  phoneInputGroup: {
    display: 'grid',
    gridTemplateColumns: '100px 1fr',
    gap: '0.75rem',
  } as React.CSSProperties,
  countryCodeSelect: {
    minHeight: 44,
    padding: '0.7rem 0.9rem',
    border: '1px solid #d8dee8',
    borderRadius: '10px',
    fontSize: '0.875rem',
    color: '#1f2937',
    backgroundColor: '#ffffff',
    cursor: 'pointer',
    fontFamily: 'inherit',
  } as React.CSSProperties,
  pincodeInputGroup: {
    display: 'grid',
    gridTemplateColumns: '1fr 50px',
    gap: '0.75rem',
    alignItems: 'flex-start',
  } as React.CSSProperties,
  eventGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
    gap: '0.75rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  eventTag: {
    padding: '0.7rem 0.9rem',
    borderRadius: '10px',
    border: '1px solid',
    fontSize: '0.875rem',
    fontWeight: '500',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center' as const,
    transition: 'all 0.3s ease',
  } as React.CSSProperties,
  eventTagActive: {
    backgroundColor: '#f3e8ff',
    borderColor: '#c4b5fd',
    color: '#6d28d9',
  } as React.CSSProperties,
  eventTagInactive: {
    backgroundColor: 'white',
    borderColor: '#e5e7eb',
    color: '#6b7280',
  } as React.CSSProperties,
  capabilitiesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '1rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  capabilityCard: {
    padding: '1rem',
    borderRadius: '12px',
    border: '1px solid',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    textAlign: 'left' as const,
    transition: 'all 0.3s ease',
    fontWeight: '500',
    fontSize: '0.875rem',
  } as React.CSSProperties,
  capabilityCardActive: {
    backgroundColor: '#f3e8ff',
    borderColor: '#c4b5fd',
    color: '#6d28d9',
  } as React.CSSProperties,
  capabilityCardInactive: {
    backgroundColor: 'white',
    borderColor: '#e5e7eb',
    color: '#6b7280',
  } as React.CSSProperties,
  serviceAreasList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  serviceAreaItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem',
    backgroundColor: '#f8fafc',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
  } as React.CSSProperties,
  areaContent: {
    flex: 1,
  } as React.CSSProperties,
  areaTitle: {
    margin: 0,
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#111827',
  } as React.CSSProperties,
  areaSubtitle: {
    margin: '0.25rem 0 0 0',
    fontSize: '0.75rem',
    color: '#6b7280',
  } as React.CSSProperties,
  helpText: {
    fontSize: '0.75rem',
    color: '#9ca3af',
    margin: '0.5rem 0 0 0',
  } as React.CSSProperties,
  errorMessage: {
    padding: '0.75rem 1rem',
    backgroundColor: '#fff1f2',
    borderRadius: '10px',
    color: '#991b1b',
    fontSize: '0.875rem',
    marginBottom: '1rem',
    border: '1px solid #fecaca',
  } as React.CSSProperties,
  submitButton: {
    width: '100%',
    minHeight: 44,
    padding: '0.8rem 1.25rem',
    background: 'linear-gradient(135deg, #7c3aed, #5b21b6)',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    fontSize: '0.875rem',
    fontWeight: '600',
    transition: 'all 0.3s ease',
    marginBottom: '1rem',
    cursor: 'pointer',
  } as React.CSSProperties,
  skipButton: {
    width: '100%',
    minHeight: 44,
    padding: '0.8rem 1.25rem',
    backgroundColor: '#f8fafc',
    color: '#475569',
    border: '1px solid #d8dee8',
    borderRadius: '10px',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    marginBottom: '1rem',
    fontFamily: 'inherit',
  } as React.CSSProperties,
  backButton: {
    width: '100%',
    minHeight: 44,
    padding: '0.8rem 1.25rem',
    backgroundColor: 'transparent',
    color: '#6d28d9',
    border: '1px solid #d8dee8',
    borderRadius: '10px',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    fontFamily: 'inherit',
  } as React.CSSProperties,
  addButton: {
    minHeight: 40,
    padding: '0.65rem 1rem',
    backgroundColor: '#0f766e',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'all 0.3s ease',
  } as React.CSSProperties,
  checkboxGroup: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '0.75rem',
  } as React.CSSProperties,
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.875rem',
    color: '#1f2937',
    cursor: 'pointer',
  } as React.CSSProperties,
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
  } as React.CSSProperties,
  radioGroup: {
    display: 'flex',
    gap: '1.5rem',
    flexDirection: 'column' as const,
  } as React.CSSProperties,
  radioLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.875rem',
    color: '#1f2937',
    cursor: 'pointer',
  } as React.CSSProperties,
  radioInput: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
  } as React.CSSProperties,
  fileInputWrapper: {
    border: '2px dashed #d1d5db',
    borderRadius: '0.5rem',
    padding: '1.5rem',
    textAlign: 'center' as const,
    backgroundColor: '#fafafa',
  } as React.CSSProperties,
  imageUploadWrapper: {
    border: '2px dashed #d1d5db',
    borderRadius: '0.5rem',
    padding: '1.5rem',
    textAlign: 'center' as const,
    backgroundColor: '#fafafa',
  } as React.CSSProperties,
  imagePreviewContainer: {
    marginTop: '1rem',
    textAlign: 'center' as const,
  } as React.CSSProperties,
  imagePreview: {
    maxWidth: '150px',
    maxHeight: '150px',
    borderRadius: '0.5rem',
    border: '1px solid #e5e7eb',
  } as React.CSSProperties,
  fileInput: {
    width: '100%',
    cursor: 'pointer',
  } as React.CSSProperties,
  fileName: {
    fontSize: '0.875rem',
    color: '#10b981',
    marginTop: '0.5rem',
    fontWeight: '600',
  } as React.CSSProperties,
  otpSentText: {
    fontSize: '0.75rem',
    color: '#6b7280',
    margin: '0.5rem 0 1rem 0',
  } as React.CSSProperties,
  resendButton: {
    width: '100%',
    minHeight: 44,
    padding: '0.8rem 1.25rem',
    background: 'linear-gradient(135deg, #7c3aed, #5b21b6)',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    fontFamily: 'inherit',
  } as React.CSSProperties,
  bankDetailsBox: {
    backgroundColor: '#f0fdf4',
    border: '1px solid #dcfce7',
    borderRadius: '0.5rem',
    padding: '1rem',
    marginTop: '0.75rem',
  } as React.CSSProperties,
  bankDetailsRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingBottom: '0.75rem',
    borderBottom: '1px solid #dcfce7',
  } as React.CSSProperties,
  bankDetailsLabel: {
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#4b5563',
    minWidth: '80px',
  } as React.CSSProperties,
  bankDetailsValue: {
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#15803d',
    textAlign: 'right' as const,
    flex: 1,
    paddingLeft: '0.5rem',
  } as React.CSSProperties,
  divider: {
    height: '1px',
    backgroundColor: '#e5e7eb',
    margin: '1.5rem 0',
  } as React.CSSProperties,
  menuForm: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e5e7eb',
    borderRadius: '14px',
    padding: '1.5rem',
    marginBottom: '1.5rem',
  } as React.CSSProperties,
  itemsList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
    marginBottom: '1.5rem',
  } as React.CSSProperties,
  listItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem',
    backgroundColor: '#f8fafc',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
  } as React.CSSProperties,
  listItemImage: {
    width: '60px',
    height: '60px',
    borderRadius: '0.5rem',
    objectFit: 'cover' as const,
  } as React.CSSProperties,
  itemContent: {
    flex: 1,
  } as React.CSSProperties,
  itemName: {
    margin: 0,
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#111827',
  } as React.CSSProperties,
  itemCategory: {
    margin: '0.25rem 0 0 0',
    fontSize: '0.75rem',
    color: '#6b7280',
  } as React.CSSProperties,
  itemDescription: {
    margin: '0.5rem 0 0 0',
    fontSize: '0.75rem',
    color: '#6b7280',
    lineHeight: '1.3',
  } as React.CSSProperties,
  itemPrice: {
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#6d28d9',
    minWidth: '60px',
    textAlign: 'right' as const,
  } as React.CSSProperties,
  menuItemsCheckList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  completeContainer: {
    textAlign: 'center' as const,
  } as React.CSSProperties,
  successIcon: {
    fontSize: '4rem',
    marginBottom: '1rem',
    display: 'inline-flex',
    width: '80px',
    height: '80px',
    backgroundColor: '#dcfce7',
    borderRadius: '50%',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#10b981',
    fontWeight: 'bold',
  } as React.CSSProperties,
  completionChecklist: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
    textAlign: 'left' as const,
    marginTop: '2rem',
    marginBottom: '2rem',
  } as React.CSSProperties,
  checklistItem: {
    display: 'flex',
    gap: '1rem',
    padding: '1rem',
    backgroundColor: '#f9fafb',
    border: '1px solid #e5e7eb',
    borderRadius: '0.75rem',
  } as React.CSSProperties,
  checklistDone: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    backgroundColor: '#dcfce7',
    color: '#10b981',
    borderRadius: '50%',
    fontWeight: 'bold',
    fontSize: '0.875rem',
    flexShrink: 0,
  } as React.CSSProperties,
  checklistPending: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    backgroundColor: '#fef3c7',
    color: '#f59e0b',
    borderRadius: '50%',
    fontWeight: 'bold',
    fontSize: '0.875rem',
    flexShrink: 0,
  } as React.CSSProperties,
  checklistTitle: {
    margin: 0,
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#111827',
  } as React.CSSProperties,
  checklistText: {
    margin: '0.25rem 0 0 0',
    fontSize: '0.75rem',
    color: '#6b7280',
  } as React.CSSProperties,
  ctaButton: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
    padding: 'clamp(0.75rem, 2vw, 1rem) 2rem',
    background: 'linear-gradient(135deg, #7c3aed, #5b21b6)',
    color: 'white',
    border: 'none',
    borderRadius: '0.75rem',
    fontSize: 'clamp(0.875rem, 2vw, 1rem)',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  } as React.CSSProperties,
  multiSelectGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))',
    gap: '0.75rem',
    marginBottom: '1rem',
  },

  multiSelectTag: {
    padding: '0.55rem 0.75rem',
    borderRadius: '10px',
    border: '1px solid',
    fontSize: '0.8rem',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    backgroundColor: 'white',
    borderColor: '#e5e7eb',
    color: '#374151',
  },

  multiSelectTagActive: {
    backgroundColor: '#f3e8ff',
    borderColor: '#c4b5fd',
    color: '#6d28d9',
  },

  multiSelectTagInactive: {
    backgroundColor: 'white',
    borderColor: '#e5e7eb',
    color: '#374151',
  },

  businessTypeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))',
    gap: '1rem',
    marginBottom: '1.5rem',
  },

  businessTypeTag: {
    padding: '0.8rem 1rem',
    borderRadius: '12px',
    border: '1px solid',
    fontSize: '0.95rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    backgroundColor: '#7c3aed',
    borderColor: '#7c3aed',
    color: 'white',
    boxShadow: '0 8px 18px rgba(124, 58, 237, 0.16)',
    textAlign: 'center',
  } as React.CSSProperties,

  businessTypeTagActive: {
    padding: '0.8rem 1rem',
    borderRadius: '12px',
    border: '1px solid',
    fontSize: '0.95rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    backgroundColor: '#7c3aed',
    borderColor: '#7c3aed',
    color: 'white',
    boxShadow: '0 10px 22px rgba(124, 58, 237, 0.18)',
    textAlign: 'center',
    transform: 'translateY(-2px)',
  } as React.CSSProperties,

  businessTypeTagInactive: {
    padding: '0.8rem 1rem',
    borderRadius: '12px',
    border: '1px solid',
    fontSize: '0.95rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    backgroundColor: 'white',
    borderColor: '#e5e7eb',
    color: '#374151',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    textAlign: 'center',
  } as React.CSSProperties,

  categoryTitle: {
    fontSize: '0.95rem',
    fontWeight: '600',
    color: '#6d28d9',
    marginBottom: '0.75rem',
    textTransform: 'capitalize',
    letterSpacing: '0.5px',
  },

  selectedCount: {
    fontSize: '0.875rem',
    color: '#10b981',
    fontWeight: '500',
    marginTop: '0.75rem',
  },

  charCounter: {
    fontSize: '0.75rem',
    color: '#9ca3af',
    marginTop: '0.25rem',
    textAlign: 'right',
  },

  formSection: {
    marginBottom: '2.5rem',
    paddingBottom: '2rem',
    borderBottom: '1px solid #e5e7eb',
  },

  sectionTitle: {
    fontSize: '1.1rem',
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: '0.5rem',
    display: 'flex',
    alignItems: 'center',
  },

  sectionSubtitle: {
    fontSize: '0.875rem',
    color: '#6b7280',
    marginBottom: '1.5rem',
    lineHeight: '1.5',
  },

  toggleSection: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '2rem',
    marginBottom: '1rem',
    flexWrap: 'wrap',
  } as React.CSSProperties,

  toggleButtons: {
    display: 'flex',
    gap: '0.75rem',
    flexWrap: 'wrap',
  },

  toggleButton: {
    padding: '0.6rem 1rem',
    borderRadius: '10px',
    border: '1px solid #e5e7eb',
    backgroundColor: 'white',
    color: '#6b7280',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  } as React.CSSProperties,

  toggleButtonActive: {
    backgroundColor: '#7c3aed',
    borderColor: '#7c3aed',
    color: 'white',
    boxShadow: '0 8px 18px rgba(124, 58, 237, 0.16)',
  } as React.CSSProperties,

  toggleButtonInactive: {
    backgroundColor: 'white',
    borderColor: '#e5e7eb',
    color: '#6b7280',
  } as React.CSSProperties,

  infoBox: {
    display: 'flex',
    alignItems: 'flex-start',
    padding: '0.875rem 1rem',
    backgroundColor: '#dbeafe',
    borderLeft: '4px solid #0284c7',
    borderRadius: '0.375rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  listTitle: {
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: '1rem',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  } as React.CSSProperties,

  deleteButton: {
    padding: '0.25rem 0.5rem',
    borderRadius: '0.375rem',
    border: 'none',
    backgroundColor: 'transparent',
    color: 'white',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '24px',
    height: '24px',
  } as React.CSSProperties,

  buttonGroup: {
    display: 'flex',
    gap: '1rem',
    marginTop: '2rem',
  } as React.CSSProperties,

  deliveryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '1.5rem',
    marginBottom: '1rem',
  } as React.CSSProperties,

  deliveryFormGroup: {
    display: 'flex',
    flexDirection: 'column',
  } as React.CSSProperties,

  documentCard: {
    padding: '1.5rem',
    border: '1px solid #e5e7eb',
    borderRadius: '0.5rem',
    marginBottom: '1.5rem',
    backgroundColor: '#fafafa',
  } as React.CSSProperties,

  documentHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '1rem',
  } as React.CSSProperties,

  documentTitle: {
    fontSize: '1rem',
    fontWeight: '600',
    color: '#1f2937',
    margin: '0 0 0.25rem 0',
  } as React.CSSProperties,

  documentDescription: {
    fontSize: '0.875rem',
    color: '#6b7280',
    margin: 0,
  } as React.CSSProperties,

  uploadSection: {
    marginTop: '1rem',
  } as React.CSSProperties,

  fileUploadBox: {
    border: '2px dashed #e5e7eb',
    borderRadius: '0.5rem',
    padding: '2rem',
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    backgroundColor: 'white',
  } as React.CSSProperties,

  uploadText: {
    fontSize: '0.95rem',
    fontWeight: '600',
    color: '#374151',
    margin: '0.5rem 0 0.25rem 0',
  } as React.CSSProperties,

  uploadSubtext: {
    fontSize: '0.875rem',
    color: '#9ca3af',
    margin: 0,
  } as React.CSSProperties,

  fileItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem',
    backgroundColor: '#f0fdf4',
    border: '1px solid #86efac',
    borderRadius: '0.375rem',
    marginTop: '1rem',
  } as React.CSSProperties,

  fileInfo: {
    display: 'flex',
    alignItems: 'center',
    flex: 1,
  } as React.CSSProperties,

  fileSize: {
    fontSize: '0.8rem',
    color: '#6b7280',
    margin: '0.25rem 0 0 0',
  } as React.CSSProperties,

  removeButton: {
    padding: '0.5rem',
    border: 'none',
    backgroundColor: '#fee2e2',
    color: '#dc2626',
    borderRadius: '0.375rem',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
  } as React.CSSProperties,

  frontBackContainer: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1.5rem',
    marginTop: '1rem',
  } as React.CSSProperties,

  frontBackSection: {
    display: 'flex',
    flexDirection: 'column',
  } as React.CSSProperties,

  frontBackTitle: {
    fontSize: '0.95rem',
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: '0.75rem',
    margin: '0 0 0.75rem 0',
  } as React.CSSProperties,

  warningMessage: {
    display: 'flex',
    alignItems: 'flex-start',
    padding: '0.875rem 1rem',
    backgroundColor: '#fef3c7',
    borderLeft: '4px solid #f59e0b',
    borderRadius: '0.375rem',
    color: '#92400e',
    fontSize: '0.875rem',
    marginBottom: '1rem',
  } as React.CSSProperties,
};
