export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    minHeight: '100vh',
    background:
      'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '1rem',
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  } as React.CSSProperties,
  content: {
    width: '100%',
    maxWidth: '700px',
    backgroundColor: 'white',
    borderRadius: '1.5rem',
    boxShadow: '0 20px 25px rgba(0, 0, 0, 0.15)',
    padding: 'clamp(1.5rem, 5vw, 3rem)',
  } as React.CSSProperties,
  progressContainer: {
    width: '100%',
    height: '4px',
    backgroundColor: '#e5e7eb',
    borderRadius: '2px',
    marginBottom: '1.5rem',
    overflow: 'hidden',
  } as React.CSSProperties,
  progressBar: {
    height: '100%',
    backgroundColor: '#f97316',
    transition: 'width 0.3s ease',
  } as React.CSSProperties,
  stepIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '1.5rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#6b7280',
  } as React.CSSProperties,
  stepNumber: {
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#f97316',
  } as React.CSSProperties,
  stepDot: {
    fontSize: '1.5rem',
    color: '#f97316',
  } as React.CSSProperties,
  loadingContainer: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'center',
    alignItems: 'center',
    background:
      'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
  } as React.CSSProperties,
  loadingSpinner: {
    width: '48px',
    height: '48px',
    border: '4px solid rgba(255, 255, 255, 0.3)',
    borderTop: '4px solid white',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
    marginBottom: '1rem',
  } as React.CSSProperties,
  loadingText: {
    color: 'white',
    fontSize: '1rem',
    margin: 0,
  } as React.CSSProperties,
  header: {
    marginBottom: '2rem',
    textAlign: 'center' as const,
  } as React.CSSProperties,
  title: {
    fontSize: 'clamp(1.5rem, 5vw, 2rem)',
    fontWeight: 'bold',
    color: '#111827',
    margin: 0,
    marginBottom: '0.5rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  } as React.CSSProperties,
  subtitle: {
    fontSize: 'clamp(0.875rem, 2vw, 1rem)',
    color: '#6b7280',
    margin: 0,
    lineHeight: '1.5',
  } as React.CSSProperties,
  profileForm: {
    marginTop: '2rem',
  } as React.CSSProperties,
  formGroup: {
    marginBottom: '1.5rem',
  } as React.CSSProperties,
  formRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
    alignItems: 'start',
  } as React.CSSProperties,
  label: {
    display: 'block',
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: '0.75rem',
  } as React.CSSProperties,
  input: {
    width: '100%',
    padding: '0.75rem 1rem',
    border: '1px solid #d1d5db',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    color: '#1f2937',
    boxSizing: 'border-box' as const,
    fontFamily: 'inherit',
  } as React.CSSProperties,
  phoneInputGroup: {
    display: 'grid',
    gridTemplateColumns: '100px 1fr',
    gap: '0.75rem',
  } as React.CSSProperties,
  countryCodeSelect: {
    padding: '0.75rem 1rem',
    border: '1px solid #d1d5db',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    color: '#1f2937',
    backgroundColor: '#f9fafb',
    cursor: 'pointer',
    fontFamily: 'inherit',
  } as React.CSSProperties,
  pincodeInputGroup: {
    display: 'grid',
    gridTemplateColumns: '1fr 50px',
    gap: '0.75rem',
    alignItems: 'flex-start',
  } as React.CSSProperties,
  eventGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
    gap: '0.75rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  eventTag: {
    padding: '0.75rem 1rem',
    borderRadius: '0.75rem',
    border: '2px solid',
    fontSize: '0.875rem',
    fontWeight: '500',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center' as const,
    transition: 'all 0.3s ease',
  } as React.CSSProperties,
  eventTagActive: {
    backgroundColor: '#dbeafe',
    borderColor: '#667eea',
    color: '#667eea',
  } as React.CSSProperties,
  eventTagInactive: {
    backgroundColor: 'white',
    borderColor: '#e5e7eb',
    color: '#6b7280',
  } as React.CSSProperties,
  capabilitiesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '1rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  capabilityCard: {
    padding: '1.25rem',
    borderRadius: '0.75rem',
    border: '2px solid',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    textAlign: 'left' as const,
    transition: 'all 0.3s ease',
    fontWeight: '500',
    fontSize: '0.875rem',
  } as React.CSSProperties,
  capabilityCardActive: {
    backgroundColor: '#dbeafe',
    borderColor: '#667eea',
    color: '#667eea',
  } as React.CSSProperties,
  capabilityCardInactive: {
    backgroundColor: 'white',
    borderColor: '#e5e7eb',
    color: '#6b7280',
  } as React.CSSProperties,
  serviceAreasList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  serviceAreaItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem',
    backgroundColor: '#f3f4f6',
    borderRadius: '0.5rem',
    border: '1px solid #e5e7eb',
  } as React.CSSProperties,
  areaContent: {
    flex: 1,
  } as React.CSSProperties,
  areaTitle: {
    margin: 0,
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#111827',
  } as React.CSSProperties,
  areaSubtitle: {
    margin: '0.25rem 0 0 0',
    fontSize: '0.75rem',
    color: '#6b7280',
  } as React.CSSProperties,
  helpText: {
    fontSize: '0.75rem',
    color: '#9ca3af',
    margin: '0.5rem 0 0 0',
  } as React.CSSProperties,
  errorMessage: {
    padding: '0.75rem 1rem',
    backgroundColor: '#fee2e2',
    borderRadius: '0.5rem',
    color: '#991b1b',
    fontSize: '0.875rem',
    marginBottom: '1rem',
    border: '1px solid #fecaca',
  } as React.CSSProperties,
  submitButton: {
    width: '100%',
    padding: '0.875rem 1.5rem',
    backgroundColor: '#f97316',
    color: 'white',
    border: 'none',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    transition: 'all 0.3s ease',
    marginBottom: '1rem',
    cursor: 'pointer',
  } as React.CSSProperties,
  skipButton: {
    width: '100%',
    padding: '0.875rem 1.5rem',
    backgroundColor: '#f3f4f6',
    color: '#6b7280',
    border: '1px solid #d1d5db',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    marginBottom: '1rem',
    fontFamily: 'inherit',
  } as React.CSSProperties,
  backButton: {
    width: '100%',
    padding: '0.875rem 1.5rem',
    backgroundColor: 'transparent',
    color: '#667eea',
    border: '1px solid #d1d5db',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    fontFamily: 'inherit',
  } as React.CSSProperties,
  addButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#10b981',
    color: 'white',
    border: 'none',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'all 0.3s ease',
  } as React.CSSProperties,
  checkboxGroup: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '0.75rem',
  } as React.CSSProperties,
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.875rem',
    color: '#1f2937',
    cursor: 'pointer',
  } as React.CSSProperties,
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
  } as React.CSSProperties,
  radioGroup: {
    display: 'flex',
    gap: '1.5rem',
    flexDirection: 'column' as const,
  } as React.CSSProperties,
  radioLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.875rem',
    color: '#1f2937',
    cursor: 'pointer',
  } as React.CSSProperties,
  radioInput: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
  } as React.CSSProperties,
  fileInputWrapper: {
    border: '2px dashed #d1d5db',
    borderRadius: '0.5rem',
    padding: '1.5rem',
    textAlign: 'center' as const,
    backgroundColor: '#fafafa',
  } as React.CSSProperties,
  imageUploadWrapper: {
    border: '2px dashed #d1d5db',
    borderRadius: '0.5rem',
    padding: '1.5rem',
    textAlign: 'center' as const,
    backgroundColor: '#fafafa',
  } as React.CSSProperties,
  imagePreviewContainer: {
    marginTop: '1rem',
    textAlign: 'center' as const,
  } as React.CSSProperties,
  imagePreview: {
    maxWidth: '150px',
    maxHeight: '150px',
    borderRadius: '0.5rem',
    border: '1px solid #e5e7eb',
  } as React.CSSProperties,
  fileInput: {
    width: '100%',
    cursor: 'pointer',
  } as React.CSSProperties,
  fileName: {
    fontSize: '0.875rem',
    color: '#10b981',
    marginTop: '0.5rem',
    fontWeight: '600',
  } as React.CSSProperties,
  otpSentText: {
    fontSize: '0.75rem',
    color: '#6b7280',
    margin: '0.5rem 0 1rem 0',
  } as React.CSSProperties,
  resendButton: {
    width: '100%',
    padding: '0.875rem 1.5rem',
    backgroundColor: '#667eea',
    color: 'white',
    border: 'none',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    fontFamily: 'inherit',
  } as React.CSSProperties,
  bankDetailsBox: {
    backgroundColor: '#f0fdf4',
    border: '1px solid #dcfce7',
    borderRadius: '0.5rem',
    padding: '1rem',
    marginTop: '0.75rem',
  } as React.CSSProperties,
  bankDetailsRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingBottom: '0.75rem',
    borderBottom: '1px solid #dcfce7',
  } as React.CSSProperties,
  bankDetailsLabel: {
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#4b5563',
    minWidth: '80px',
  } as React.CSSProperties,
  bankDetailsValue: {
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#15803d',
    textAlign: 'right' as const,
    flex: 1,
    paddingLeft: '0.5rem',
  } as React.CSSProperties,
  divider: {
    height: '1px',
    backgroundColor: '#e5e7eb',
    margin: '1.5rem 0',
  } as React.CSSProperties,
  menuForm: {
    backgroundColor: '#f9fafb',
    border: '1px solid #e5e7eb',
    borderRadius: '1rem',
    padding: '1.5rem',
    marginBottom: '1.5rem',
  } as React.CSSProperties,
  itemsList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
    marginBottom: '1.5rem',
  } as React.CSSProperties,
  listItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem',
    backgroundColor: '#f3f4f6',
    borderRadius: '0.5rem',
    border: '1px solid #e5e7eb',
  } as React.CSSProperties,
  listItemImage: {
    width: '60px',
    height: '60px',
    borderRadius: '0.5rem',
    objectFit: 'cover' as const,
  } as React.CSSProperties,
  itemContent: {
    flex: 1,
  } as React.CSSProperties,
  itemName: {
    margin: 0,
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#111827',
  } as React.CSSProperties,
  itemCategory: {
    margin: '0.25rem 0 0 0',
    fontSize: '0.75rem',
    color: '#6b7280',
  } as React.CSSProperties,
  itemDescription: {
    margin: '0.5rem 0 0 0',
    fontSize: '0.75rem',
    color: '#6b7280',
    lineHeight: '1.3',
  } as React.CSSProperties,
  itemPrice: {
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#f97316',
    minWidth: '60px',
    textAlign: 'right' as const,
  } as React.CSSProperties,
  menuItemsCheckList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  completeContainer: {
    textAlign: 'center' as const,
  } as React.CSSProperties,
  successIcon: {
    fontSize: '4rem',
    marginBottom: '1rem',
    display: 'inline-flex',
    width: '80px',
    height: '80px',
    backgroundColor: '#dcfce7',
    borderRadius: '50%',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#10b981',
    fontWeight: 'bold',
  } as React.CSSProperties,
  completionChecklist: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
    textAlign: 'left' as const,
    marginTop: '2rem',
    marginBottom: '2rem',
  } as React.CSSProperties,
  checklistItem: {
    display: 'flex',
    gap: '1rem',
    padding: '1rem',
    backgroundColor: '#f9fafb',
    border: '1px solid #e5e7eb',
    borderRadius: '0.75rem',
  } as React.CSSProperties,
  checklistDone: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    backgroundColor: '#dcfce7',
    color: '#10b981',
    borderRadius: '50%',
    fontWeight: 'bold',
    fontSize: '0.875rem',
    flexShrink: 0,
  } as React.CSSProperties,
  checklistPending: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    backgroundColor: '#fef3c7',
    color: '#f59e0b',
    borderRadius: '50%',
    fontWeight: 'bold',
    fontSize: '0.875rem',
    flexShrink: 0,
  } as React.CSSProperties,
  checklistTitle: {
    margin: 0,
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#111827',
  } as React.CSSProperties,
  checklistText: {
    margin: '0.25rem 0 0 0',
    fontSize: '0.75rem',
    color: '#6b7280',
  } as React.CSSProperties,
  ctaButton: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
    padding: 'clamp(0.75rem, 2vw, 1rem) 2rem',
    backgroundColor: '#f97316',
    color: 'white',
    border: 'none',
    borderRadius: '0.75rem',
    fontSize: 'clamp(0.875rem, 2vw, 1rem)',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  } as React.CSSProperties,
  multiSelectGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))',
    gap: '0.75rem',
    marginBottom: '1rem',
  },

  multiSelectTag: {
    padding: '0.5rem 0.75rem',
    borderRadius: '0.375rem',
    border: '2px solid',
    fontSize: '0.8rem',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    backgroundColor: 'white',
    borderColor: '#e5e7eb',
    color: '#374151',
  },

  multiSelectTagActive: {
    backgroundColor: '#dbeafe',
    borderColor: '#667eea',
    color: '#1e40af',
  },

  multiSelectTagInactive: {
    backgroundColor: 'white',
    borderColor: '#e5e7eb',
    color: '#374151',
  },


  businessTypeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))',
    gap: '1rem',
    marginBottom: '1.5rem',
  },

  businessTypeTag: {
    padding: '0.875rem 1.25rem',
    borderRadius: '0.5rem',
    border: '2px solid',
    fontSize: '0.95rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    backgroundColor: '#667eea',
    borderColor: '#667eea',
    color: 'white',
    boxShadow: '0 2px 8px rgba(102, 126, 234, 0.3)',
    textAlign: 'center',
  } as React.CSSProperties,

  businessTypeTagActive: {
    padding: '0.875rem 1.25rem',
    borderRadius: '0.5rem',
    border: '2px solid',
    fontSize: '0.95rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    backgroundColor: '#667eea',
    borderColor: '#667eea',
    color: 'white',
    boxShadow: '0 4px 12px rgba(102, 126, 234, 0.4)',
    textAlign: 'center',
    transform: 'translateY(-2px)',
  } as React.CSSProperties,

  businessTypeTagInactive: {
    padding: '0.875rem 1.25rem',
    borderRadius: '0.5rem',
    border: '2px solid',
    fontSize: '0.95rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    backgroundColor: 'white',
    borderColor: '#e5e7eb',
    color: '#374151',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    textAlign: 'center',
  } as React.CSSProperties,


  categoryTitle: {
    fontSize: '0.95rem',
    fontWeight: '600',
    color: '#667eea',
    marginBottom: '0.75rem',
    textTransform: 'capitalize',
    letterSpacing: '0.5px',
  },

  selectedCount: {
    fontSize: '0.875rem',
    color: '#10b981',
    fontWeight: '500',
    marginTop: '0.75rem',
  },

  charCounter: {
    fontSize: '0.75rem',
    color: '#9ca3af',
    marginTop: '0.25rem',
    textAlign: 'right',
  },

  formSection: {
    marginBottom: '2.5rem',
    paddingBottom: '2rem',
    borderBottom: '1px solid #e5e7eb',
  },

  sectionTitle: {
    fontSize: '1.1rem',
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: '0.5rem',
    display: 'flex',
    alignItems: 'center',
  },

  sectionSubtitle: {
    fontSize: '0.875rem',
    color: '#6b7280',
    marginBottom: '1.5rem',
    lineHeight: '1.5',
  },

  toggleSection: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '2rem',
    marginBottom: '1rem',
    flexWrap: 'wrap',
  } as React.CSSProperties,

  toggleButtons: {
    display: 'flex',
    gap: '0.75rem',
    flexWrap: 'wrap',
  },

  toggleButton: {
    padding: '0.625rem 1.25rem',
    borderRadius: '0.375rem',
    border: '2px solid #e5e7eb',
    backgroundColor: 'white',
    color: '#6b7280',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  } as React.CSSProperties,

  toggleButtonActive: {
    backgroundColor: '#667eea',
    borderColor: '#667eea',
    color: 'white',
    boxShadow: '0 2px 8px rgba(102, 126, 234, 0.3)',
  } as React.CSSProperties,

  toggleButtonInactive: {
    backgroundColor: 'white',
    borderColor: '#e5e7eb',
    color: '#6b7280',
  } as React.CSSProperties,

  infoBox: {
    display: 'flex',
    alignItems: 'flex-start',
    padding: '0.875rem 1rem',
    backgroundColor: '#dbeafe',
    borderLeft: '4px solid #0284c7',
    borderRadius: '0.375rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  listTitle: {
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: '1rem',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  } as React.CSSProperties,


  deleteButton: {
    padding: '0.25rem 0.5rem',
    borderRadius: '0.375rem',
    border: 'none',
    backgroundColor: 'transparent',
    color: 'white',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '24px',
    height: '24px',
  } as React.CSSProperties,

  buttonGroup: {
    display: 'flex',
    gap: '1rem',
    marginTop: '2rem',
  } as React.CSSProperties,

  deliveryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '1.5rem',
    marginBottom: '1rem',
  } as React.CSSProperties,

  deliveryFormGroup: {
    display: 'flex',
    flexDirection: 'column',
  } as React.CSSProperties,

};

